version: '3.8'

services:
  ecommerce-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=/data/ecommerce.db
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_EXPIRY=24h
      - ENABLE_RATE_LIMIT=true
    volumes:
      # Persist database data
      - ecommerce-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - ecommerce-network

volumes:
  ecommerce-data:
    driver: local

networks:
  ecommerce-network:
    driver: bridge
